### PR TITLE
Code documentation fix

### PR DESCRIPTION
**Pull request by keopx**
Code documentation fix

### CODE REVIEW

**Comment by overint** [comment]
I don't see the problem, the comments are correctly marked, why would you need 2 apostrophes?

**Comment by keopx** [comment]
The two asterisk are docblocks typo document style.

You can check:

https://phpdoc.org/docs/latest/guides/docblocks.html

**Comment by overint** [comment]
All of the methods have docblocks, but the changed ones are just comments? Forgive me if I am missing something, but I was under the understanding that you only use the double asterisk for parsable docblocks/comments (usually for methods, but sometimes for properties), which these are not.

**Comment by keopx** [comment]
Regardless of what you are discussing, the php doc documentation says that both asterisks are necessary.

https://phpdoc.org/docs/latest/getting-started/your-first-set-of-documentation.html#what-does-a-docblock-look-like

**Comment by overint** [comment]
But doing that causes incorrect documentation to be generated.
https://puu.sh/sAf3b/3b391ed98d.png

**Comment by overint** [comment]
I've created a pull request with complete PHPdoc coverage if you want to continue the discussion there.

**Comment by overint** [comment]
I'm going to close this, feel free to continue on #69

**Comment by keopx** [comment]
Thanks @overint

**Pull request closed without merging**
