### PR TITLE
Update paypal_ipn.pl

### PR DESCRIPTION
**Pull request by sflex**
Now uses strict, warnings, CGI.pm, refactored/golfed some code and prints the right header if it dies. With suggestions on security and operations

### CODE REVIEW

**Comment by overint** [comment]
Hey @sflex 
Thanks for your contribution.  Couple of requests before we can get this merged.

- Since PayPal [will soon begin forcing SSL on IPN postbacks](https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1916&viewlocale=en_US),  so I think it would be best to have the sample require HTTPS and tls1.2
- Update the postback URLs to the new dedicated ones [found here](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNImplementation/).

**Comment by sflex** [comment]
I hope the updates to the sample file are sufficient now.

**Comment by overint** [comment]
Thanks for that. I'm not able to test perl, can you confirm it's still working?

**Comment by sflex** [comment]
I syntax checked it on 5.8 and 5.22, so the code will compile on Perl versions 5.8 and up.

My current sandbox account is configured for chain payment, so if you give me a day to reconfigure for IPN and setup a server with SSL and TLS1.2. I can then confirm it was fully tested.

The only one problem it could have is with SSL through LWP module, some times the module IO::Socket::SSL needs to be installed or updated.

**Comment by sflex** [comment]
It works on HTTP and HTTPS. One main concern others and myself had was the fact that CGI.pm decodes the URL/POST content and the content sent back to PayPal may need to be encoded. But it seems that the IPN simulator doesn't care about the encoding.

I had to learn on my own that PayPal will not let you use a self-signed certificate and their standards for certificates are being updated also. [PayPal SSL Certificate Changes](https://devblog.paypal.com/paypal-ssl-certificate-changes/)  

Hope that helps.

**Comment by overint** [comment]
I've merged it in alongside the current sample so users have a choice of either. Thanks!
https://github.com/paypal/ipn-code-samples/commit/3dfcd67e480ee654629ee1110e44a4b253350c8d

**Pull request closed without merging**
