### PR TITLE
rawurlencode/rawurlencode fixes #51

### LINKED ISSUE #51: ipn-php sample always return INVALID
Hello, i'm testing the php script with paypal ipn simulator, it always return "INVALID".

Has PayPal changed something ? it worked flawless 1 month ago

Can you check ? Thanks

ipn.log

```
[2016-05-26 11:36 Europe/Rome] HTTP request of validation request:POST /cgi-bin/webscr HTTP/1.1
Host: www.sandbox.paypal.com
Accept: */*
Connection: Close
Content-Length: 937
Content-Type: application/x-www-form-urlencoded

 for IPN payload: cmd=_notify-validate&payment_type=instant&payment_date=Thu+May+26+2016+11%3A25%3A05+GMT+0200+%28ora+legale+Europa+occidentale%29&payment_status=Completed&address_status=confirmed&payer_status=verified&first_name=John&last_name=Smith&payer_email=buyer%40paypalsandbox.com&payer_id=TESTBUYERID01&address_name=John+Smith&address_country=United+States&address_country_code=US&address_zip=95131&address_state=CA&address_city=San+Jose&address_street=123+any+street&business=seller%40paypalsandbox.com&receiver_email=seller%40paypalsandbox.com&receiver_id=seller%40paypalsandbox.com&residence_country=US&item_name1=something&item_number1=AK-1234&tax=2.02&mc_currency=USD&mc_fee=0.44&mc_gross=12.34&mc_gross_1=12.34&mc_handling=2.06&mc_handling1=1.67&mc_shipping=3.02&mc_shipping1=1.02&txn_type=cart&txn_id=322624560&notify_version=2.1&custom=xyz123&invoice=abc1234&test_ipn=1&verify_sign=AC0mHADgHZCOp9yb3KBEhFHcfK.EATIofsAI4BOoej.lZWFOFc6-mBBm
[2016-05-26 11:36 Europe/Rome] HTTP response of validation request: HTTP/1.1 200 OK
Date: Thu, 26 May 2016 09:36:35 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
Set-Cookie: c9MWDuvPtT9GIMyPc3jwol1VSlO=q3EDoFz3xzU8qwoeStT1WLy3rVSqCC04ggXDb9E-sqhzz5kz-MUa5dNOebpwNbpDMUZk-KCXoEU7756JGR3CqhVVE_PJsBISV2WI7CXDoBxXHOafDzdzaaBnpO6j3V_hDp0X9wQS6MZOr7xBW4IdCz_qX_keXORuA9j4FCzlu024HwYDJ7OaT4BztsXbxJfWdnic7cKrOdDhbMqYPGIPB-g94iiIgzG9J-rMNtjtkOtocgsIGtzogBH2wY2hDA1XjbhsyUMy5rRcJdHfe-rrgitkPD8e9d8AakOh7sptGIUfjyNTy1ZkkCT5UKJ3X2Qs1O6SvnRGyewxf5EZ8MO727pqB2pnzME1FRLcSMpbns6BNlk9jVIIYpKYrE8kRHrQrtyuwxabvThHgaRaNcn5jaj5sOXBDuEecOw1EFRUXE0Kv5dl5Qup0y66ju8; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: cookie_check=yes; expires=Sun, 24-May-2026 09:36:36 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: navcmd=_notify-validate; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: navlns=0.0; expires=Sat, 26-May-2018 09:36:36 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: Apache=10.72.108.11.1464255395837996; path=/; expires=Sat, 19-May-46 09:36:35 GMT
Vary: Accept-Encoding,User-Agent
Connection: close
HTTP_X_PP_AZ_LOCATOR: sandbox.slc
Paypal-Debug-Id: a68dc41cc80e0
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.WEB.1%26silo_version%3D1880%26app%3Dappdispatcher%26TIME%3D2747483735%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Thu, 26 May 2016 10:06:36 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Strict-Transport-Security: max-age=14400
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

INVALID
[2016-05-26 11:36 Europe/Rome] Invalid IPN: cmd=_notify-validate&payment_type=instant&payment_date=Thu+May+26+2016+11%3A25%3A05+GMT+0200+%28ora+legale+Europa+occidentale%29&payment_status=Completed&address_status=confirmed&payer_status=verified&first_name=John&last_name=Smith&payer_email=buyer%40paypalsandbox.com&payer_id=TESTBUYERID01&address_name=John+Smith&address_country=United+States&address_country_code=US&address_zip=95131&address_state=CA&address_city=San+Jose&address_street=123+any+street&business=seller%40paypalsandbox.com&receiver_email=seller%40paypalsandbox.com&receiver_id=seller%40paypalsandbox.com&residence_country=US&item_name1=something&item_number1=AK-1234&tax=2.02&mc_currency=USD&mc_fee=0.44&mc_gross=12.34&mc_gross_1=12.34&mc_handling=2.06&mc_handling1=1.67&mc_shipping=3.02&mc_shipping1=1.02&txn_type=cart&txn_id=322624560&notify_version=2.1&custom=xyz123&invoice=abc1234&test_ipn=1&verify_sign=AC0mHADgHZCOp9yb3KBEhFHcfK.EATIofsAI4BOoej.lZWFOFc6-mBBm
```

### PR DESCRIPTION
**Pull request by davidearl**
Paypal requires exactly the same raw post headers, and they use raw
encoding/decoding (always %20, not +). This means that urldecode in the
example gets time zones wrong (the + in +0100 for e.g. gets treated as a
space), and it re-encodes incorrectly with +'s where there were %20's.
(Why on earth isn't this done properly at the Paypal end to look at the
individual variables rather than the raw data!)

### CODE REVIEW

**Comment by davidearl** [comment]
Actually, it turned out that it works for the IPN tester on the dashboard, but not for the live version. PayPal appears to have different encoding methods for the tester and the live code. Doh! raw_urldecode works for the test, url_decode for the live (and sandbox live). Makes a nonsense of the tester really!

**Comment by pp-randy** [comment]
@davidearl so it is working for the simulator but not the actual IPN?

**Comment by davidearl** [comment]
That appears to be the case, and vice-versa. There appears to be no solution that will work reliably in both! Of course, I was testing using the simulator to start with, which is why I thought the existing code was not working.

**Comment by davidearl** [comment]
I had a very long exchange with paypal support about this, but even at the end of it I did not believe the person I was dealing with understood the difference between character encoding and percent encoding of URLs, so I gave up trying.

**Comment by pp-randy** [comment]
@davidearl Thank you for the information and the pull request.  I will look into this further.

**Comment by jaypatel512** [comment]
Hey @davidearl !

Thanks for investigating on this. It looks like the most reliable fix for this would be update tester to do the same url encoding/decoding as the live version.

**Comment by overint** [comment]
I too experienced some encoding issues, particularity with the `payment_date` post param. It's formatting make it hard (the + is incorrectly encoded as a space by PHP). 
Here's the relevant code in my IPN repo:
https://github.com/overint/php-paypal-ipn/blob/master/src/PaypalIPN.php#L77

**Comment by overint** [comment]
No longer required since we have a new PHP sample.
Thanks 😄

**Pull request closed without merging**
