### PR TITLE
Show how to auto add fields to MySQL

### PR DESCRIPTION
**Pull request by GaryFunk**
PayPal uses so many different fields for many different notifications.  It's difficult to keep the table properly updated. This fie helps solve that issue.

### CODE REVIEW

**Comment by overint** [comment]
Hi Gary
Thanks for the pull request, but I think this is a bit to specific to have in the sample repo. 
You can view a list of IPN fields [here](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNandPDTVariables/)

I'll leave it open so the other members can have a look.

**Comment by overint** [comment]
@pp-randy Would like your thoughts on this. IMO a bit specific for a sample I think.

**Comment by pp-randy** [comment]
The pull request is appreciated; however, this would no longer check if the IPN is verified.  The check here is to make sure the IPN is from PayPal https://github.com/paypal/ipn-code-samples/blob/master/coldfusion/paypal_ipn.cfm#L13.  

I also advise not to alter table columns in any web accessible script.  Ideally, you would know the columns you need from the IPN and just collect those.  If you need the full IPN maybe log to a file after its verified or store the full body.

**Comment by pp-randy** [comment]
I do appreciate the pull request; however, per my comments I am closing this pull request at this time. I am happy to review any further pulls.

**Pull request closed without merging**
