### PR TITLE
fix code indenting & make it actually work

### PR DESCRIPTION
**Pull request by walterbax**

### CODE REVIEW

**Comment by overint** [comment]
Hi!
Thanks for the pull, did you test the sample to confirm it works?

**Comment by walterbax** [comment]
I have, it works great with the sandbox url and the simulator returning VERIFIED.

still having an issue when only switching the url to live, always get INVALID so far. unrelated to the pull, I just altered empty space.

**Comment by overint** [comment]
Does the latest commit fix the problems in the live environment?

**Comment by walterbax** [comment]
sorry if I did that wrong let me know, I made another commit, that makes it work on live yes.

**Pull request merged**
